import type {
  ActivityCategory,
  ActivityTemplate,
  LevelDefinition,
  QuestInstanceStatus,
  RestDayType,
  RewardRedemptionStatus,
  StarterQuest,
  StarterReward,
  Weekday,
} from "./types";

export const WEEKDAYS = [
  "monday",
  "tuesday",
  "wednesday",
  "thursday",
  "friday",
  "saturday",
  "sunday",
] as const satisfies readonly Weekday[];

export const ACTIVITY_CATEGORIES = [
  "Learning",
  "Physical",
  "Creative",
  "Music",
  "Life Skills",
  "Screen",
  "Custom",
] as const satisfies readonly ActivityCategory[];

export const REST_DAY_TYPES = [
  "rest_day",
  "sick_day",
  "travel_day",
  "camp_day",
  "family_day",
  "parent_excused_day",
] as const satisfies readonly RestDayType[];

export const QUEST_INSTANCE_STATUSES = [
  "not_started",
  "in_progress",
  "submitted",
  "completed",
  "denied",
] as const satisfies readonly QuestInstanceStatus[];

export const REWARD_REDEMPTION_STATUSES = [
  "requested",
  "approved",
  "denied",
  "approved_for_later",
  "cancelled",
] as const satisfies readonly RewardRedemptionStatus[];

export const LEVELS = [
  { level: 1, xp: 0, title: "Trail Scout" },
  { level: 2, xp: 75, title: "Quest Rookie" },
  { level: 3, xp: 175, title: "Map Reader" },
  { level: 4, xp: 300, title: "Brave Adventurer" },
  { level: 5, xp: 450, title: "Forest Explorer" },
  { level: 6, xp: 625, title: "Treasure Seeker" },
  { level: 7, xp: 825, title: "Camp Champion" },
  { level: 8, xp: 1050, title: "Skill Builder" },
  { level: 9, xp: 1300, title: "Dragon Helper" },
  { level: 10, xp: 1575, title: "Quest Knight" },
  { level: 11, xp: 1875, title: "Adventure Captain" },
  { level: 12, xp: 2200, title: "Star Collector" },
  { level: 13, xp: 2550, title: "Challenge Master" },
  { level: 14, xp: 2925, title: "Dragon Tamer" },
  { level: 15, xp: 3325, title: "Summer Hero" },
  { level: 16, xp: 3750, title: "Legendary Scout" },
  { level: 17, xp: 4000, title: "Quest Guardian" },
  { level: 18, xp: 4250, title: "Treasure Master" },
  { level: 19, xp: 4525, title: "Summer Legend" },
  { level: 20, xp: 4800, title: "Legendary Adventurer" },
] as const satisfies readonly LevelDefinition[];

export const ACTIVITY_TEMPLATES = [
  {
    id: "reading",
    name: "Reading",
    icon: "\u{1F4DA}",
    category: "Learning",
    duration_minutes: 30,
    approval_mode: "auto",
  },
  {
    id: "outdoor-play",
    name: "Outdoor Play",
    icon: "\u{1F3C3}",
    category: "Physical",
    duration_minutes: 30,
    approval_mode: "auto",
  },
  {
    id: "exercise",
    name: "Exercise",
    icon: "\u{1F4AA}",
    category: "Physical",
    duration_minutes: 30,
    approval_mode: "auto",
  },
  {
    id: "drawing",
    name: "Drawing",
    icon: "\u{1F3A8}",
    category: "Creative",
    duration_minutes: 20,
    approval_mode: "auto",
  },
  {
    id: "music-practice",
    name: "Music Practice",
    icon: "\u{1F3B5}",
    category: "Music",
    duration_minutes: 30,
    approval_mode: "auto",
  },
  {
    id: "chores",
    name: "Chores",
    icon: "\u{1F9F9}",
    category: "Life Skills",
    duration_minutes: 20,
    approval_mode: "parent",
  },
  {
    id: "tidy-room",
    name: "Tidy Room",
    icon: "\u{1F6CF}\u{FE0F}",
    category: "Life Skills",
    duration_minutes: 15,
    approval_mode: "parent",
  },
  {
    id: "screen-time",
    name: "Screen Time",
    icon: "\u{1F3AE}",
    category: "Screen",
    duration_minutes: 45,
    approval_mode: "auto",
  },
] as const satisfies readonly ActivityTemplate[];

export const STARTER_QUESTS = [
  {
    id: "starter-reading",
    name: "Reading",
    icon: "\u{1F4DA}",
    category: "Learning",
    duration_minutes: 30,
    active_days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    suggested_time_window: "morning",
    completion_deadline: "before lunch",
    approval_mode: "auto",
    xp_value: 45,
    coin_value: 9,
    unlock_mode: "always",
    prerequisite_quest_ids: [],
    parent_note: null,
  },
  {
    id: "starter-outdoor-play",
    name: "Outdoor Play",
    icon: "\u{1F3C3}",
    category: "Physical",
    duration_minutes: 30,
    active_days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    suggested_time_window: "afternoon",
    completion_deadline: "before dinner",
    approval_mode: "auto",
    xp_value: 45,
    coin_value: 9,
    unlock_mode: "always",
    prerequisite_quest_ids: [],
    parent_note: null,
  },
  {
    id: "starter-chores",
    name: "Chores",
    icon: "\u{1F9F9}",
    category: "Life Skills",
    duration_minutes: 20,
    active_days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    suggested_time_window: "before dinner",
    completion_deadline: "before dinner",
    approval_mode: "parent",
    xp_value: 30,
    coin_value: 6,
    unlock_mode: "always",
    prerequisite_quest_ids: [],
    parent_note: null,
  },
  {
    id: "starter-drawing",
    name: "Drawing",
    icon: "\u{1F3A8}",
    category: "Creative",
    duration_minutes: 20,
    active_days: ["saturday", "sunday"],
    suggested_time_window: "afternoon",
    completion_deadline: "end of day",
    approval_mode: "auto",
    xp_value: 30,
    coin_value: 6,
    unlock_mode: "always",
    prerequisite_quest_ids: [],
    parent_note: null,
  },
  {
    id: "starter-screen-time",
    name: "Screen Time",
    icon: "\u{1F3AE}",
    category: "Screen",
    duration_minutes: 45,
    active_days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
    suggested_time_window: "evening",
    completion_deadline: "before screen time or end of day",
    approval_mode: "auto",
    xp_value: 0,
    coin_value: 0,
    unlock_mode: "after_multiple",
    prerequisite_quest_ids: ["starter-reading", "starter-outdoor-play"],
    parent_note: "Complete Reading and Outdoor Play first.",
  },
] as const satisfies readonly StarterQuest[];

export const STARTER_REWARDS = [
  {
    id: "reward-pick-dessert",
    name: "Pick dessert",
    description: "Choose dessert for the family.",
    icon: "\u{1F370}",
    cost: 20,
    active: true,
  },
  {
    id: "reward-pick-dinner",
    name: "Pick dinner",
    description: "Choose dinner for a parent-approved night.",
    icon: "\u{1F35D}",
    cost: 30,
    active: true,
  },
  {
    id: "reward-stay-up-late",
    name: "Stay up 30 minutes late",
    description: "Use on a parent-approved night.",
    icon: "\u{1F319}",
    cost: 40,
    active: true,
  },
  {
    id: "reward-extra-screen-time",
    name: "Extra 30 minutes screen time",
    description: "Add 30 minutes of parent-approved screen time.",
    icon: "\u{1F3AE}",
    cost: 45,
    active: true,
  },
  {
    id: "reward-movie-night",
    name: "Movie night pick",
    description: "Choose the next family movie.",
    icon: "\u{1F3AC}",
    cost: 60,
    active: true,
  },
  {
    id: "reward-ice-cream-trip",
    name: "Ice cream trip",
    description: "Go out for ice cream together.",
    icon: "\u{1F366}",
    cost: 80,
    active: true,
  },
  {
    id: "reward-bowling-trip",
    name: "Bowling trip",
    description: "Plan a family bowling trip.",
    icon: "\u{1F3B3}",
    cost: 200,
    active: true,
  },
  {
    id: "reward-big-family-outing",
    name: "Big family outing",
    description: "Choose a bigger family outing to celebrate.",
    icon: "\u{1F39F}\u{FE0F}",
    cost: 300,
    active: true,
  },
] as const satisfies readonly StarterReward[];
